### ISSUE TITLE
Error when pasting

### ISSUE THREAD

**Issue by msnjuegos** [mankinence/ImageResizer#17]
I have problems when I am trying to paste [an image](https://upload.wikimedia.org/wikipedia/commons/5/52/Lawrence_of_Arabia%27s_map%2C_presented_to_the_Eastern_Committee_of_the_War_Cabinet_in_November_1918.jpg) in a note field (with the shortcut). For example, if I try to paste the image in {{Back}} or {{Extra}} field, I get the following error. But, sometimes works pasting the image in {{Front}} field and then copy it in {{Back}} field.
 
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-25 22:35:43
Add-ons possibly involved: ⁨ImageResizer⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/editor.py", line 264, in on_activated
  File "/home/./.local/share/Anki2/addons21/1214357311/__init__.py", line 192, in <lambda>
    self.addButton(func = lambda s = self: imageResizer(self),
  File "/home//.local/share/Anki2/addons21/1214357311/__init__.py", line 167, in imageResizer
    mime = checkAndResize(mime, self)
  File "/home//.local/share/Anki2/addons21/1214357311/__init__.py", line 249, in checkAndResize
    im = resize(mime.imageData())
  File "/home//.local/share/Anki2/addons21/1214357311/__init__.py", line 139, in resize
    logger.debug('image before resizing, width: {}, height: {}'.format(im.width(), im.height()))
AttributeError: 'NoneType' object has no attribute 'width'

```

**Comment by searene** [comment]
Thanks for reporting. I've reproduced this issue. It seems to only happen on Linux. It works just fine on Windows. I'm looking into it.

**Comment by searene** [comment]
Hi,

I think I have fixed this issue, could you update this addon and try again?

**Comment by msnjuegos** [comment]
Thanks for your quick response. Unfortunately the problem persists, at least with certain images. Maybe there could be something related to the resolution? With these images ([1](https://upload.wikimedia.org/wikipedia/commons/c/cb/Broadway_tower_edit.jpg), [2](https://upload.wikimedia.org/wikipedia/commons/0/02/Eichh%C3%B6rnchen_D%C3%BCsseldorf_Hofgarten_edit.jpg)) it works, but with these ([1](https://upload.wikimedia.org/wikipedia/commons/5/52/Lawrence_of_Arabia%27s_map%2C_presented_to_the_Eastern_Committee_of_the_War_Cabinet_in_November_1918.jpg), [2](https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/New_York_City_at_night_HDR.jpg/1920px-New_York_City_at_night_HDR.jpg)) it doesn't work and the workaround from the previous post that works for me, no longer works. 

The error displayed is the same:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-26 22:48:47
Add-ons possibly involved: ⁨ImageResizer⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/editor.py", line 264, in on_activated
  File "/home//.local/share/Anki2/addons21/1214357311/__init__.py", line 222, in <lambda>
    self.addButton(func = lambda s = self: imageResizer(self),
  File "/home//.local/share/Anki2/addons21/1214357311/__init__.py", line 197, in imageResizer
    mime = checkAndResize(mime, self)
  File "/home//.local/share/Anki2/addons21/1214357311/__init__.py", line 272, in checkAndResize
    im = resize(mime.imageData())
  File "/home//.local/share/Anki2/addons21/1214357311/__init__.py", line 140, in resize
    logger.debug('image before resizing, width: {}, height: {}'.format(im.width(), im.height()))
AttributeError: 'NoneType' object has no attribute 'width'

```

**Comment by searene** [comment]
Thanks, I've reproduced the issue. PyQt tells me that it has the image but I have nowhere to get it. I'm trying to work out a solution. For now, I just bypass this kind of image, the pasting at least works, albeit it's not resized. You can update the addon again to clear the error message for now.

**Comment by searene** [comment]
I just uploaded a new version, could you update this plugin and have a test?

**Comment by msnjuegos** [comment]
Now it works perfect! Thanks for your prompt response.
